---
# tasks file for ansible-percona_mysql

- name: Load the OS specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- include: repository_{{ ansible_os_family }}.yml

- name: Ensure percona mysql is installed
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ __percona_mysql_pkgs }}"

- name: Ensure log directory is separate from datafiles (for zfs integration)
  file:
    path: "/var/lib/mysql-log"
    owner: "mysql"
    group: "mysql"
    mode: "0750"
    state: "directory"
  when: percona_mysql_zfs

- name: Setup mysqld configuration
  template:
    src: "mysqld.cnf.j2"
    dest: "{{ __percona_mysql_conf_dir }}/percona-server.conf.d/mysqld.cnf"
  notify: restart mysql

- name: Ensure mysql is running so I can secure it
  service:
    name: "{{ __percona_mysql_service }}"
    state: started

- name: Ensure installation is secured
  include: secure.yml

- name: If there are vhosts variable available setup mysql users and db
  include: users_db.yml
  with_items: "{{ vhosts }}"
  loop_control:
    loop_var: outer_item
  when: vhosts is defined
